//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEPProjekatPS120511.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public string UserId { get; set; }
        public long ProductId { get; set; }
        public int Status { get; set; }
        public int Type { get; set; }
        public System.DateTime Date { get; set; }
    }
}
