//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEPProjekatPS120511.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SW_Product
    {
        public long IDProduct { get; set; }
        public string Name { get; set; }
        public string Tag { get; set; }
        public string Description { get; set; }
        public byte[] Logo { get; set; }
        public byte[] Image { get; set; }
        public double Price { get; set; }
        public int Deleted { get; set; }
    }
}
